### ISSUE TITLE
[Feat] Update version on Ansible Galaxy

### ISSUE THREAD

**Issue by ItsMyPain** [vitabaks/autobase#1337]
### Problem

Hi! I apologize right away for my broken English, I'm still learning it.

I want to use ansible galaxy collection vitabaks.autobase (https://galaxy.ansible.com/ui/repo/published/vitabaks/autobase/?version=2.4.1) but I am facing a problem

```
TASK [vitabaks.autobase.packages : Install TimescaleDB package]*************************************************************
[ERROR]: The `loop` value must resolve to a 'list', not 'str'.
Origin: /home/doctor/.ansible/collections/ansible_collections/vitabaks/autobase/roles/packages/tasks/extensions.yml:12:9
10     name: "{{ item }}"
11     state: present
12     loop: "{{ timescaledb_package }}" 
             ^ column 9
Provide a list of items/templates, or a template resolving to a list.
fatal: [db01]: FAILED! => {"msg": "The `loop` value must resolve to a 'list', not 'str'."}
fatal: [db02]: FAILED! => {"msg": "The `loop` value must resolve to a 'list', not 'str'."}
```

After searching a bit on the Internet, I found that this problem has already been solved here
https://github.com/vitabaks/autobase/issues/1299
This issue was related to the Ansible 12 update.
This bug has already been closed and the changes are merged in the repository.
https://github.com/vitabaks/autobase/pull/1279
I even found where the line that caused me the problem was deleted.

<img width="2519" height="719" alt="Image" src="https://github.com/user-attachments/assets/dc93643d-0903-4fef-837a-c5478e87dc15" />
However, when I download the source file from Ansible Galaxy, there is still no updated code, which is why I encounter a problem.

<img width="1249" height="544" alt="Image" src="https://github.com/user-attachments/assets/8b643c78-2840-4a36-bb29-7892d2407d4b" />

This can also be understood by the time:
1. The pull request was merged at 

<img width="832" height="202" alt="Image" src="https://github.com/user-attachments/assets/260c5827-e80c-4ea6-8b02-601e82c5858b" />

2. But last update of collection was at

<img width="428" height="136" alt="Image" src="https://github.com/user-attachments/assets/a04cba57-92cc-4d80-8619-9ad2ec76ae6e" />

### Description

Can you please release a new version of the ansible Galaxy collection that fixes this issue?

### Importance

must have

**Comment by vitabaks** [comment]
Ansible 12 support will be added in autobase 2.5, which is scheduled to be released this month.

For now, just use ansible 11.

**Comment by vitabaks** [comment]
Done.

**Comment by Raphyyy** [comment]
Hello @vitabaks 
It seems that the error is still there today with the last updates : 

```
# git pull github master
From https://github.com/vitabaks/autobase
 * branch            master     -> FETCH_HEAD
Already up to date.

# ansible-community --version
Ansible community version 12.2.0

# ansible-playbook playbooks/deploy_pgcluster.yml [...]
[...]
TASK [vitabaks.autobase.packages : Install TimescaleDB package] **********************************************************************************************************************************************
[ERROR]: The `loop` value must resolve to a 'list', not 'str'.
Origin: /root/.ansible/collections/ansible_collections/vitabaks/autobase/roles/packages/tasks/extensions.yml:12:9

10     name: "{{ item }}"
11     state: present
12   loop: "{{ timescaledb_package }}"
           ^ column 9
```

**Comment by vitabaks** [comment]
@Raphyyy Judging by the error, you are still using the old version of the code. 

Try installing the [ansible collection](https://github.com/vitabaks/autobase/blob/master/automation/README.md#using-this-collection) (if you prefer it):

```
ansible-galaxy collection install vitabaks.autobase:2.5.0
```

or use the docker installer, example:

```
docker run --rm -it \
  -e ANSIBLE_SSH_ARGS="-F none" \
  -e ANSIBLE_INVENTORY=/project/inventory \
  -v $PWD:/project \
  -v $HOME/.ssh:/root/.ssh \
  autobase/automation:2.5.0 \
    ansible-playbook deploy_pgcluster.yml
```

**Comment by Raphyyy** [comment]
Oops indeed, my apologies.
I am trying to fork your solution because I need to do some changes for my need but it still looks complicated to me to tell ansible to use local files instead of collections through ansible-galaxy.

**Comment by vitabaks** [comment]
>  I need to do some changes

What exactly are you missing from the main version?

**Comment by Raphyyy** [comment]
few stuff, typically this https://github.com/vitabaks/autobase/issues/1343 I would like to try to implement

**Comment by vitabaks** [comment]
Feel free to suggest PR.
